<?php
	require('globals.php');
	require_once './plugins/PHPExcel/Classes/PHPExcel.php';
	
	if ($_SERVER["REQUEST_METHOD"]=="POST"){
		$dtype="";
		$dtype=$_POST["dtype"];
		// Create new PHPExcel object
		$objPHPExcel = new PHPExcel();
		// Set properties
		$objPHPExcel->getProperties()->setCreator(WA_TITLE)
				 ->setLastModifiedBy(WA_TITLE)
				 ->setTitle(ucwords(strtolower($_SESSION["host_name"]))." Document")
				 ->setSubject(ucwords(strtolower($_SESSION["host_name"])))
				 ->setDescription("This document was generated by the ".WA_TITLE." for ".ucwords(strtolower($_SESSION["host_name"])))
				 ->setKeywords(ucwords(strtolower($_SESSION["host_name"])))
				 ->setCategory(ucwords(strtolower($_SESSION["host_name"]))." Documents");
		// Add some data
		$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A1', strtoupper($_SESSION["host_name"]))
					->setCellValue('A2', 'LIBRARY BOOKS RECORDS - '.strtoupper($dtype).' LIST');
		
		if($dtype=='all'){
			$sql = mysqli_query($mysqli,"SELECT * FROM books ORDER BY bAccNo ASC");
			$n = 1;
			$BStyle = array(
					  'borders' => array(
						'allborders' => array(
						  'style' => PHPExcel_Style_Border::BORDER_THIN
						)
					  )
					);
					
			$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A4', 'ACCESS NUMBER')
						->setCellValue('B4', 'TITLE')
						->setCellValue('C4', 'AUTHOR')
						->setCellValue('D4', 'PUBLISHER')
						->setCellValue('E4', 'DESCRIPTION')
						->setCellValue('F4', 'EDITION')
						->setCellValue('G4', 'CARTEGORY')
						->setCellValue('H4', 'POPUB')
						->setCellValue('I4', 'YOPUB');
				$no=5;
			while($data = mysqli_fetch_assoc($sql)){
				$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A'.$no, " ".$data['bAccNo'])
					->setCellValue('B'.$no, $data['bTitle'])
					->setCellValue('C'.$no, $data['bAuthor'])
					->setCellValue('D'.$no, $data['bPublisher'])
					->setCellValue('E'.$no, $data['bBlurb'])
					->setCellValue('F'.$no, $data['bEdition'])
					->setCellValue('G'.$no, $data['bCartegory'])
					->setCellValue('H'.$no, $data['bPoPub'])
					->setCellValue('I'.$no, $data['bYoPub']);
				$n++;
				$no++;
			}
			$objPHPExcel->getActiveSheet()->mergeCells('A1:I1');
			$objPHPExcel->getActiveSheet()->mergeCells('A2:I2');
			$objPHPExcel->getActiveSheet()->getStyle('A1:I4')->getFont()->setBold(true);
			//autosize column width
			foreach(range('A','I') as $columnID) {
				$objPHPExcel->getActiveSheet()->getColumnDimension($columnID)
					->setAutoSize(true);
			}
			//set borders
			$objPHPExcel->getActiveSheet()->getStyle('A4:I'.($no-1))->applyFromArray($BStyle);
		}
		elseif($dtype=='issue'){
			$n = 1;
			$BStyle = array(
					  'borders' => array(
						'allborders' => array(
						  'style' => PHPExcel_Style_Border::BORDER_THIN
						)
					  )
					);
					
			$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A4', 'ACCESS NUMBER')
						->setCellValue('B4', 'TITLE')
						->setCellValue('C4', 'AUTHOR')
						->setCellValue('D4', 'PUBLISHER')
						->setCellValue('E4', 'ISSUED TO')
						->setCellValue('F4', 'NUMBER')
						->setCellValue('G4', 'DESCRIPTION')
						->setCellValue('H4', 'EDITION')
						->setCellValue('I4', 'CARTEGORY');
				$no=5;
			
			$squer="SELECT * FROM issue WHERE iState=0;";
			$resl=mysqli_query($mysqli,$squer);
			while ($r=mysqli_fetch_array($resl)){
				$q2="SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1;";
				$res2=mysqli_query($mysqli,$q2);
				while ($rw2=mysqli_fetch_array($res2)){
					
				}
				
				$sql = mysqli_query($mysqli,"SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1");
				while($data = mysqli_fetch_assoc($sql)){
					$luname=$lunumb='';
					$q3="SELECT * FROM libcusts WHERE LID=".$r['SID']." LIMIT 1;";
					$res3=mysqli_query($mysqli,$q3);
					while ($rw3=mysqli_fetch_array($res3)){
						$luname=ucwords(strtolower($rw3["LName"]));
						$lunumb=$rw3["LNumb"];
					}
					$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A'.$no, " ".$data['bAccNo'])
						->setCellValue('B'.$no, $data['bTitle'])
						->setCellValue('C'.$no, $data['bAuthor'])
						->setCellValue('D'.$no, $data['bPublisher'])
						->setCellValue('E'.$no, $luname)
						->setCellValue('F'.$no, $lunumb)
						->setCellValue('G'.$no, $data['bBlurb'])
						->setCellValue('H'.$no, $data['bEdition'])
						->setCellValue('I'.$no, $data['bCartegory']);
					$n++;
					$no++;
				}
			}
			
			$objPHPExcel->getActiveSheet()->mergeCells('A1:I1');
			$objPHPExcel->getActiveSheet()->mergeCells('A2:I2');
			$objPHPExcel->getActiveSheet()->getStyle('A1:I4')->getFont()->setBold(true);
			//autosize column width
			foreach(range('A','I') as $columnID) {
				$objPHPExcel->getActiveSheet()->getColumnDimension($columnID)
					->setAutoSize(true);
			}
			//set borders
			$objPHPExcel->getActiveSheet()->getStyle('A4:I'.($no-1))->applyFromArray($BStyle);
		}
		elseif($dtype=='lost'){
			$n = 1;
			$BStyle = array(
					  'borders' => array(
						'allborders' => array(
						  'style' => PHPExcel_Style_Border::BORDER_THIN
						)
					  )
					);
					
			$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A4', 'ACCESS NUMBER')
						->setCellValue('B4', 'TITLE')
						->setCellValue('C4', 'AUTHOR')
						->setCellValue('D4', 'PUBLISHER')
						->setCellValue('E4', 'DESCRIPTION')
						->setCellValue('F4', 'EDITION')
						->setCellValue('G4', 'CARTEGORY')
						->setCellValue('H4', 'POPUB')
						->setCellValue('I4', 'YOPUB');
				$no=5;
			
			$squer="SELECT * FROM issue WHERE iState=2;";
			$resl=mysqli_query($mysqli,$squer);
			while ($r=mysqli_fetch_array($resl)){
				$q2="SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1;";
				$res2=mysqli_query($mysqli,$q2);
				while ($rw2=mysqli_fetch_array($res2)){
					
				}
				
				$sql = mysqli_query($mysqli,"SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1");
				while($data = mysqli_fetch_assoc($sql)){
					$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A'.$no, " ".$data['bAccNo'])
						->setCellValue('B'.$no, $data['bTitle'])
						->setCellValue('C'.$no, $data['bAuthor'])
						->setCellValue('D'.$no, $data['bPublisher'])
						->setCellValue('E'.$no, $data['bBlurb'])
						->setCellValue('F'.$no, $data['bEdition'])
						->setCellValue('G'.$no, $data['bCartegory'])
						->setCellValue('H'.$no, $data['bPoPub'])
						->setCellValue('I'.$no, $data['bYoPub']);
					$n++;
					$no++;
				}
			}
			
			$objPHPExcel->getActiveSheet()->mergeCells('A1:I1');
			$objPHPExcel->getActiveSheet()->mergeCells('A2:I2');
			$objPHPExcel->getActiveSheet()->getStyle('A1:I4')->getFont()->setBold(true);
			//autosize column width
			foreach(range('A','I') as $columnID) {
				$objPHPExcel->getActiveSheet()->getColumnDimension($columnID)
					->setAutoSize(true);
			}
			//set borders
			$objPHPExcel->getActiveSheet()->getStyle('A4:I'.($no-1))->applyFromArray($BStyle);
		}
		elseif($dtype=='overdue'){
			$n = 1;
			$BStyle = array(
					  'borders' => array(
						'allborders' => array(
						  'style' => PHPExcel_Style_Border::BORDER_THIN
						)
					  )
					);
					
			$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A4', 'ACCESS NUMBER')
						->setCellValue('B4', 'TITLE')
						->setCellValue('C4', 'AUTHOR')
						->setCellValue('D4', 'PUBLISHER')
						->setCellValue('E4', 'ISSUED TO')
						->setCellValue('F4', 'NUMBER')
						->setCellValue('G4', 'DESCRIPTION')
						->setCellValue('H4', 'EDITION')
						->setCellValue('I4', 'CARTEGORY');
				$no=5;
			
			$squer="SELECT * FROM issue WHERE (iTimeS+INTERVAL iDuration DAY)<CURDATE();";
			$resl=mysqli_query($mysqli,$squer);
			while ($r=mysqli_fetch_array($resl)){
				$q2="SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1;";
				$res2=mysqli_query($mysqli,$q2);
				while ($rw2=mysqli_fetch_array($res2)){
					
				}
				
				$sql = mysqli_query($mysqli,"SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1");
				while($data = mysqli_fetch_assoc($sql)){
					$luname=$lunumb='';
					$q3="SELECT * FROM libcusts WHERE LID=".$r['SID']." LIMIT 1;";
					$res3=mysqli_query($mysqli,$q3);
					while ($rw3=mysqli_fetch_array($res3)){
						$luname=ucwords(strtolower($rw3["LName"]));
						$lunumb=$rw3["LNumb"];
					}
					$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A'.$no, " ".$data['bAccNo'])
						->setCellValue('B'.$no, $data['bTitle'])
						->setCellValue('C'.$no, $data['bAuthor'])
						->setCellValue('D'.$no, $data['bPublisher'])
						->setCellValue('E'.$no, $luname)
						->setCellValue('F'.$no, $lunumb)
						->setCellValue('G'.$no, $data['bBlurb'])
						->setCellValue('H'.$no, $data['bEdition'])
						->setCellValue('I'.$no, $data['bCartegory']);
					$n++;
					$no++;
				}
			}
			
			$objPHPExcel->getActiveSheet()->mergeCells('A1:I1');
			$objPHPExcel->getActiveSheet()->mergeCells('A2:I2');
			$objPHPExcel->getActiveSheet()->getStyle('A1:I4')->getFont()->setBold(true);
			//autosize column width
			foreach(range('A','I') as $columnID) {
				$objPHPExcel->getActiveSheet()->getColumnDimension($columnID)
					->setAutoSize(true);
			}
			//set borders
			$objPHPExcel->getActiveSheet()->getStyle('A4:I'.($no-1))->applyFromArray($BStyle);
		}
		elseif($dtype=='compensated'){
			$n = 1;
			$BStyle = array(
					  'borders' => array(
						'allborders' => array(
						  'style' => PHPExcel_Style_Border::BORDER_THIN
						)
					  )
					);
					
			$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A4', 'ACCESS NUMBER')
						->setCellValue('B4', 'TITLE')
						->setCellValue('C4', 'AUTHOR')
						->setCellValue('D4', 'PUBLISHER')
						->setCellValue('E4', 'DESCRIPTION')
						->setCellValue('F4', 'EDITION')
						->setCellValue('G4', 'CARTEGORY')
						->setCellValue('H4', 'POPUB')
						->setCellValue('I4', 'YOPUB');
				$no=5;
			
			$squer="SELECT * FROM issue WHERE iState=3;";
			$resl=mysqli_query($mysqli,$squer);
			while ($r=mysqli_fetch_array($resl)){
				$q2="SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1;";
				$res2=mysqli_query($mysqli,$q2);
				while ($rw2=mysqli_fetch_array($res2)){
					
				}
				
				$sql = mysqli_query($mysqli,"SELECT * FROM books WHERE BID=".$r['BID']." LIMIT 1");
				while($data = mysqli_fetch_assoc($sql)){
					$objPHPExcel->setActiveSheetIndex(0)
						->setCellValue('A'.$no, " ".$data['bAccNo'])
						->setCellValue('B'.$no, $data['bTitle'])
						->setCellValue('C'.$no, $data['bAuthor'])
						->setCellValue('D'.$no, $data['bPublisher'])
						->setCellValue('E'.$no, $data['bBlurb'])
						->setCellValue('F'.$no, $data['bEdition'])
						->setCellValue('G'.$no, $data['bCartegory'])
						->setCellValue('H'.$no, $data['bPoPub'])
						->setCellValue('I'.$no, $data['bYoPub']);
					$n++;
					$no++;
				}
			}
			
			$objPHPExcel->getActiveSheet()->mergeCells('A1:I1');
			$objPHPExcel->getActiveSheet()->mergeCells('A2:I2');
			$objPHPExcel->getActiveSheet()->getStyle('A1:I4')->getFont()->setBold(true);
			//autosize column width
			foreach(range('A','I') as $columnID) {
				$objPHPExcel->getActiveSheet()->getColumnDimension($columnID)
					->setAutoSize(true);
			}
			//set borders
			$objPHPExcel->getActiveSheet()->getStyle('A4:I'.($no-1))->applyFromArray($BStyle);
		}
		
		// Rename sheet
		$objPHPExcel->getActiveSheet()->setTitle(strtoupper($dtype));
		// Set active sheet index to the first sheet, so Excel opens this as the first sheet
		$objPHPExcel->setActiveSheetIndex(0);
		
		ob_end_clean();
		
		// Redirect output to a client�s web browser (Excel2007)
		header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
		header('Content-Disposition: attachment;filename="Books Records.xlsx"');
		header('Cache-Control: max-age=0');
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('php://output');
		//exit;
	}
	
	
?>